


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(576, 553)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_mulakatlar = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_mulakatlar.setGeometry(QtCore.QRect(370, 30, 101, 61))
        self.label_mulakatlar.setObjectName("label_mulakatlar")
        self.buton_ara = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buton_ara.setGeometry(QtCore.QRect(40, 90, 101, 31))
        self.buton_ara.setObjectName("buton_ara")
        self.line_arama = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_arama.setGeometry(QtCore.QRect(170, 90, 371, 31))
        self.line_arama.setObjectName("line_arama")
        self.buton_gonderilen = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buton_gonderilen.setGeometry(QtCore.QRect(40, 140, 221, 61))
        self.buton_gonderilen.setObjectName("buton_gonderilen")
        self.buton_gelen = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buton_gelen.setGeometry(QtCore.QRect(320, 140, 221, 61))
        self.buton_gelen.setObjectName("buton_gelen")
        self.buton_cikis = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buton_cikis.setGeometry(QtCore.QRect(40, 220, 101, 41))
        self.buton_cikis.setObjectName("buton_cikis")
        self.buton_tercih = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buton_tercih.setGeometry(QtCore.QRect(450, 220, 91, 41))
        self.buton_tercih.setObjectName("buton_tercih")
        self.table_tarihler = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.table_tarihler.setGeometry(QtCore.QRect(40, 300, 501, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_tarihler.sizePolicy().hasHeightForWidth())
        self.table_tarihler.setSizePolicy(sizePolicy)
        self.table_tarihler.setMinimumSize(QtCore.QSize(501, 0))
        self.table_tarihler.setMaximumSize(QtCore.QSize(501, 16777215))
        self.table_tarihler.setSizeIncrement(QtCore.QSize(0, 0))
        self.table_tarihler.setObjectName("table_tarihler")
        self.table_tarihler.setColumnCount(3)
        self.table_tarihler.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_tarihler.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_tarihler.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_tarihler.setHorizontalHeaderItem(2, item)
        self.table_tarihler.horizontalHeader().setDefaultSectionSize(166)
        self.button_carpi = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_carpi.setGeometry(QtCore.QRect(544, 0, 31, 23))
        self.button_carpi.setObjectName("button_carpi")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 576, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_mulakatlar.setText(_translate("MainWindow", "      MÜLAKATLAR"))
        self.buton_ara.setText(_translate("MainWindow", "ARA"))
        self.line_arama.setText(_translate("MainWindow", "ARANACAK METNİ GİRİNİZ!"))
        self.buton_gonderilen.setText(_translate("MainWindow", "PROJESİ GÖNDERİLMİŞ OLANLAR"))
        self.buton_gelen.setText(_translate("MainWindow", "PROJESİ GELMİŞ OLANLAR"))
        self.buton_cikis.setText(_translate("MainWindow", "EXIT"))
        self.buton_tercih.setText(_translate("MainWindow", "TERCİHLER"))
        item = self.table_tarihler.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ad Soyad"))
        item = self.table_tarihler.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Proje Gönderiliş Tarihi"))
        item = self.table_tarihler.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Proje Geliş Tarihi"))
        self.button_carpi.setText(_translate("MainWindow", "X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
